#!/bin/sh
# cdfi
# Current Directory & Files Information >> cdfi
# Writes out the current working dir then lists all of the files and dirs from it

echo -n "\n\033[34m"
pwd
echo -n "\n\033[1;34m"
ls -alh | grep ^d | awk '{print $0;$9}'
echo -n "\033[1;32m"
ls -alph | grep -v / | grep -v '^total'
echo -n "\033[0m\n"
